name=CH32X035 Examples
version=0.2.0
author=esehehelp
maintainer=esehehelp
sentence=Examples for the CH32X035F7P6 Micro Devboard.
paragraph=Basic GPIO and native USB Serial examples for the board.
category=Other
architectures=ch32x035f7p6
includes=CH32X035_Examples.h
